// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class Auction
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public decimal StartingPrice { get; set; }

    public decimal ReservePrice { get; set; }

    public decimal EstimateMinPrice { get; set; }

    public decimal EstimateMaxPrice { get; set; }

    public DateTime EndsAt { get; set; }

    public bool IsArchived { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Product Product { get; set; }
}