// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class AuctionPurchase
{
    public int Id { get; set; }

    public int? SellerId { get; set; }

    public int? BuyerId { get; set; }

    public int? AuctionId { get; set; }

    public decimal? FinalPrice { get; set; }

    public DateTime? PurchasedAt { get; set; }

    public virtual Auction Auction { get; set; }

    public virtual User Buyer { get; set; }

    public virtual User Seller { get; set; }
}