// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class AuctionPurchase
{
    public int PurchaseId { get; set; }

    public int? SellerId { get; set; }

    public int? BuyerId { get; set; }

    public int? AuctionId { get; set; }

    public float? FinalPrice { get; set; }

    public DateTime? PurchaseTime { get; set; }

    public Auction Auction { get; set; }

    public User Buyer { get; set; }

    public User Seller { get; set; }
}