// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class Auction
{
    public int AuctionId { get; set; }

    public DateTime? EndTime { get; set; }

    public int? FirstPrice { get; set; }

    public int? ProductId { get; set; }

    public float? EstimatedMinimum { get; set; }

    public float? EstimatedMaximum { get; set; }

    public bool? Archived { get; set; }

    public ICollection<AuctionPurchase> AuctionPurchases { get; set; } = new List<AuctionPurchase>();

    public ICollection<Bid> Bids { get; set; } = new List<Bid>();

    public Product Product { get; set; }
}