// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class AuctionPurchase
{
    public int purchaseid { get; set; }

    public int? sellerid { get; set; }

    public int? buyerid { get; set; }

    public int? auctionid { get; set; }

    public float? finalprice { get; set; }

    public DateTime? purchasetime { get; set; }

    public virtual Auction auction { get; set; }

    public virtual User buyer { get; set; }

    public virtual User seller { get; set; }
}