// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class Bid
{
    public int bidid { get; set; }

    public int? auctionid { get; set; }

    public int? bidderid { get; set; }

    public float? bidamount { get; set; }

    public virtual Auction auction { get; set; }

    public virtual User bidder { get; set; }
}