// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class Bid
{
    public int BidId { get; set; }

    public int? AuctionId { get; set; }

    public int? BidderId { get; set; }

    public float? BidAmount { get; set; }

    public Auction Auction { get; set; }

    public User Bidder { get; set; }
}