// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class InstaBuy
{
    public int InstaId { get; set; }

    public float? Price { get; set; }

    public bool? Archived { get; set; }

    public ICollection<InstaBuyPurchase> InstabuyPurchases { get; set; } = new List<InstaBuyPurchase>();
}