// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class InstaBuy
{
    public int Id { get; set; }

    public decimal? Price { get; set; }

    public bool? IsArchived { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<InstaBuyPurchase> InstaBuyPurchases { get; set; } = new List<InstaBuyPurchase>();

    public virtual Product Product { get; set; }
}