// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class Instabuy
{
    public int instaid { get; set; }

    public float? price { get; set; }

    public bool? archived { get; set; }

    public virtual ICollection<InstabuyPurchase> instabuypurchases { get; set; } = new List<InstabuyPurchase>();
}