// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class InstabuyPurchase
{
    public int purchaseid { get; set; }

    public int? userid { get; set; }

    public int? instaid { get; set; }

    public DateTime? purchasetime { get; set; }

    public virtual Instabuy insta { get; set; }
}