// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class InstaBuyPurchase
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? InstaId { get; set; }

    public DateTime? PurchaseTime { get; set; }

    public InstaBuy Insta { get; set; }
}