// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class Post
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string Text { get; set; }

    public DateTime? TimePosted { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();

    public virtual ICollection<Picture> Pictures { get; set; } = new List<Picture>();

    public virtual User User { get; set; }
}