// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class Product
{
    public int Id { get; set; }

    public decimal? Height { get; set; }

    public decimal? Width { get; set; }

    public decimal? Depth { get; set; }

    public decimal? Weight { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? ArtistId { get; set; }

    public virtual User Artist { get; set; }
}