// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class Product
{
    public int Id { get; set; }

    public decimal Height { get; set; }

    public decimal Width { get; set; }

    public decimal Depth { get; set; }

    public decimal Weight { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Artist { get; set; }

    public int SellerId { get; set; }

    public int? Year { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User Seller { get; set; }
}