// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class user
{
    public int userid { get; set; }

    public string email { get; set; }

    public string pass { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public int UPID { get; set; }

    public string bio { get; set; }

    public string country { get; set; }

    public string personal_link { get; set; }

    public virtual ICollection<auctionpurchase> auctionpurchasebuyers { get; set; } = new List<auctionpurchase>();

    public virtual ICollection<auctionpurchase> auctionpurchasesellers { get; set; } = new List<auctionpurchase>();

    public virtual ICollection<bid> bids { get; set; } = new List<bid>();

    public virtual ICollection<product> products { get; set; } = new List<product>();
}