// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public class User
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Bio { get; set; }

    public string Country { get; set; }

    public string PersonalLink { get; set; }

    public virtual ICollection<AuctionPurchase> auctionpurchasebuyers { get; set; } = new List<AuctionPurchase>();

    public virtual ICollection<AuctionPurchase> auctionpurchasesellers { get; set; } = new List<AuctionPurchase>();

    public virtual ICollection<Bid> bids { get; set; } = new List<Bid>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}