// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Data.Models;

public partial class DbFixedPriceListingPurchase
{
    public int Id { get; set; }

    public int BuyerId { get; set; }

    public int FixedPriceListingId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual DbUser Buyer { get; set; }

    public virtual DbFixedPriceListing FixedPriceListing { get; set; }
}