// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Data.Models;

public partial class DbFixedPriceListing
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public decimal Price { get; set; }

    public bool IsArchived { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<DbFixedPriceListingPurchase> FixedPriceListingPurchases { get; set; } = new List<DbFixedPriceListingPurchase>();

    public virtual DbProduct Product { get; set; }
}