// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Data.Models;

public partial class DbPost
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Text { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<DbComment> Comments { get; set; } = new List<DbComment>();

    public virtual ICollection<DbLike> Likes { get; set; } = new List<DbLike>();

    public virtual DbUser User { get; set; }
}